apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: chuck
  name: chuck
  namespace: chuk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chuck
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chuck
    spec:
      containers:
      - image: 132527949143.dkr.ecr.us-east-1.amazonaws.com/chuck:latest
        name: chuck
        ports:
        - containerPort: 5000
        resources: {}
status: {}
